apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-music
  labels:
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-music
    apis.apps.tanzu.vmware.com/register-api: "true"
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: api_descriptor
    value:
      type: openapi # We currently support openapi, aysncapi, graphql, grpc
      location:
        path: "/v3/api-docs"  # The path to the api documentation
      system: spring-music
      owner: default-team   # The team that owns this
      description: "A set of API endpoints to manage the resources within the spring-music app."
  source:
    git:
      url: https://github.com/PeterEltgroth/spring-music.git
      ref:
        branch: tap1.3